version: "3.8"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=adventure
      - POSTGRES_USER=adv_user
      - POSTGRES_PASSWORD=lsdkjfw93idj!ks
  web:
    build: .
    command: bash -c "python manage.py migrate --no-input && python manage.py loaddata seed.json && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
